services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $rootDir: '%kernel.project_dir%'
            
    PiWeb\PiCRUD\:
        resource: '../../*'
        exclude: '../../{Annotation,DependencyInjection,Event,Migrations,Tests,Kernel.php}'

    serializer.normalizer.structured_data:
        class: PiWeb\PiCRUD\Serializer\StructuredData\DefaultStructuredDataSerializer
        tags:
            - { name: serializer.normalizer, priority: -910 }

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]