services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $rootDir: '%kernel.project_dir%'
            
    PiWeb\PiCRUD\:
        resource: '../../*'
        exclude: '../../{Annotation,DependencyInjection,Event,Migrations,Tests,Kernel.php}'

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    PiWeb\PiCRUD\DataCollector\SeoCollector:
        tags:
            - name: data_collector
              template: '@PiCRUD/data_collector/seo_collector.html.twig'
              id: PiWeb\PiCRUD\DataCollector\SeoCollector