services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $rootDir: '%kernel.project_dir%'
            
    PiWeb\PiCRUD\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Event,Migrations,Tests,Kernel.php}'

    block.admin_menu:
        class: PiWeb\PiCRUD\Block\AdminMenuBlock
        tags:
            - { name: sonata.block }

    block.item:
        class: PiWeb\PiCRUD\Block\ItemBlock
        tags:
            - { name: sonata.block }
